name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello"
      TARGET: "World"
      MESSAGE: "${{ env.GREETING }}, ${{ env.TARGET }}!"
    steps:
      - name: Display Message
        run: echo "$MESSAGE"
